SET NUMERIC_ROUNDABORT OFF
GO
SET ANSI_PADDING, ANSI_WARNINGS, CONCAT_NULL_YIELDS_NULL, ARITHABORT, QUOTED_IDENTIFIER, ANSI_NULLS ON
GO
PRINT N'Dropping [dbo].[job]'
GO
DROP TABLE [dbo].[job]
GO
PRINT N'Altering [dbo].[person]'
GO
ALTER TABLE [dbo].[person] DROP
COLUMN [email]
GO

