SET NUMERIC_ROUNDABORT OFF
GO
SET ANSI_PADDING, ANSI_WARNINGS, CONCAT_NULL_YIELDS_NULL, ARITHABORT, QUOTED_IDENTIFIER, ANSI_NULLS ON
GO
PRINT N'Dropping [dbo].[vw_items]'
GO
DROP VIEW [dbo].[vw_items]
GO
PRINT N'Dropping [dbo].[AddItem]'
GO
DROP PROCEDURE [dbo].[AddItem]
GO

