SET NUMERIC_ROUNDABORT OFF
GO
SET ANSI_PADDING, ANSI_WARNINGS, CONCAT_NULL_YIELDS_NULL, ARITHABORT, QUOTED_IDENTIFIER, ANSI_NULLS ON
GO
PRINT N'Dropping [dbo].[roles]'
GO
DROP TABLE [dbo].[roles]
GO
PRINT N'Dropping [dbo].[clients]'
GO
DROP TABLE [dbo].[clients]
GO

