SET NUMERIC_ROUNDABORT OFF
GO
SET ANSI_PADDING, ANSI_WARNINGS, CONCAT_NULL_YIELDS_NULL, ARITHABORT, QUOTED_IDENTIFIER, ANSI_NULLS ON
GO
PRINT N'Altering [dbo].[person]'
GO
ALTER TABLE [dbo].[person] ADD
[email] [VARCHAR] (100) NULL
GO
PRINT N'Creating [dbo].[job]'
GO
CREATE TABLE [dbo].[job]
(
[id] [INT] NOT NULL,
[title] [VARCHAR] (100) NOT NULL
)
GO

